#!/bin/sh
# OpenVPN up/down hook to apply/remove DNS from foreign_option_* variables.
# This avoids parsing logs and runs precisely when tunnel state changes.
set -eu

MODE="${script_type:-}"
RESOLV="/etc/resolv.conf"
BACKUP="/etc/resolv.conf.pre-openvpn"

log() {
  printf '[%s] [dns-hook] %s\n' "$(date -u +"%Y-%m-%dT%H:%M:%SZ")" "$*" >&2
}

# Collect pushed DNS from foreign_option_* env vars
collect_dns() {
  env | grep -E '^foreign_option_[0-9]+=' | sed 's/^foreign_option_[0-9]\+=//' |
    awk 'BEGIN{FS=" ";} toupper($1)=="DHCP-OPTION" && toupper($2)=="DNS" {print $3}' |
    awk 'NF>0' | awk '!seen[$0]++'
}

apply_dns() {
  dns_list=$(collect_dns || true)
  if [ -z "$dns_list" ]; then
    log "no pushed DNS found; leaving resolv.conf as-is"
    exit 0
  fi
  if [ ! -f "$BACKUP" ] && [ -f "$RESOLV" ]; then
    cp -f "$RESOLV" "$BACKUP"
  fi
  {
    echo "# generated by openvpn up-hook";
    for ns in $dns_list; do
      echo "nameserver $ns";
    done
  } >"$RESOLV"
  log "applied DNS: $dns_list"
}

restore_dns() {
  if [ -f "$BACKUP" ]; then
    cp -f "$BACKUP" "$RESOLV"
    rm -f "$BACKUP"
    log "restored original resolv.conf"
  else
    log "no backup resolv.conf to restore"
  fi
}

case "$MODE" in
  up|route-up)
    apply_dns ;;
  down|down-pre)
    restore_dns ;;
  *)
    # default to apply on unknown mode
    apply_dns ;;
esac

